version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14

jobs:
  init-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  check-formatting:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run format:check
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Build package
          command: npm run build
      - run:
          name: Copy files for release
          command: cp package.json LICENSE README.md .npmrc ./lib
      - run:
          name: Publish package
          command: cd lib && npm publish

workflows:
  version: 2
  format-check-and-deploy:
    jobs:
      - init-dependencies:
          filters:
            tags:
              only: /.*/
      - check-formatting:
          requires:
            - init-dependencies
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - check-formatting
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
